# Generated by Django 4.2.8 on 2026-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_type',
            field=models.CharField(choices=[('general', 'General'), ('student_leader', 'Student Leader')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='leader_organization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='leader_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
