# Generated by Django 4.2.8 on 2026-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Must be a TIP (@tip.edu.ph) or Gmail (@gmail.com) email', max_length=254, unique=True),
        ),
    ]
