# Generated by Django 4.2.8 on 2026-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Common Inquiries',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chats', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('satisfaction_rate', models.FloatField(default=0.0)),
                ('chats_change', models.FloatField(default=0.0)),
                ('users_change', models.FloatField(default=0.0)),
                ('response_time_change', models.FloatField(default=0.0)),
                ('satisfaction_change', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Metrics',
            },
        ),
        migrations.CreateModel(
            name='ResponseTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_response_time', models.FloatField()),
                ('min_response_time', models.FloatField()),
                ('max_response_time', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Response Time Data',
                'ordering': ['-date'],
            },
        ),
    ]
