# Generated by Django 4.2.8 on 2026-04-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('billing', 'Billing'), ('account', 'Account'), ('features', 'Features'), ('security', 'Security'), ('integrations', 'Integrations'), ('support', 'Support')], default='general', max_length=100),
        ),
    ]
